apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  labels:
    app: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-app
        image: devapp/order-app:v5
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_HOST
          value: "postgres.infrastructure.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "devappdb"
        - name: DB_USERNAME
          value: "devappuser"
        - name: DB_PASSWORD
          value: "mypassword"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.infrastructure.svc.cluster.local:9092"
        - name: REDIS_HOST
          value: "redis.infrastructure.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis.infrastructure.svc.cluster.local"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: "http://keycloak.infrastructure.svc.cluster.local:8080/realms/devapp"
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
          value: "http://keycloak.infrastructure.svc.cluster.local:8080/realms/devapp/protocol/openid-connect/certs"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-app
  labels:
    app: order-app
spec:
  selector:
    app: order-app
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
